package com.example.mha.news.view.viewmodel

import androidx.lifecycle.ViewModel
import com.example.mha.news.adapterlist.currency_adapterlist.CurrencyList
import com.example.mha.news.model.currencymodel.Base
import com.example.mha.news.service.currency.CurrencyApiService
import retrofit2.Call
import retrofit2.Callback
import retrofit2.Response

class CurrencyViewModel : ViewModel() {
    var currencyErrorMessage = true
    var currencyModel: Base? = null
    val currencyList = ArrayList<CurrencyList>()
    fun getData() {
        CurrencyApiService.getData().enqueue(object : Callback<Base> {
            override fun onResponse(call: Call<Base>, response: Response<Base>) {
                currencyModel = response.body()
                currencyListAdd()
                currencyErrorMessage = false
            }

            override fun onFailure(call: Call<Base>, t: Throwable) {
                currencyErrorMessage = true
            }
        })
    }

    private fun currencyListAdd() {
        currencyList.add(CurrencyList("TRY", currencyModel!!.quotes.uSDTRY))
        currencyList.add(CurrencyList("AED", currencyModel!!.quotes.uSDAED))
        currencyList.add(CurrencyList("AFN", currencyModel!!.quotes.uSDAFN))
        currencyList.add(CurrencyList("ALL", currencyModel!!.quotes.uSDALL))
        currencyList.add(CurrencyList("AMD", currencyModel!!.quotes.uSDAMD))
        currencyList.add(CurrencyList("ANG", currencyModel!!.quotes.uSDANG))
        currencyList.add(CurrencyList("AOA", currencyModel!!.quotes.uSDAOA))
        currencyList.add(CurrencyList("ARS", currencyModel!!.quotes.uSDARS))
        currencyList.add(CurrencyList("AUD", currencyModel!!.quotes.uSDAUD))
        currencyList.add(CurrencyList("AWG", currencyModel!!.quotes.uSDAWG))
        currencyList.add(CurrencyList("AZN", currencyModel!!.quotes.uSDAZN))
        currencyList.add(CurrencyList("BAM", currencyModel!!.quotes.uSDBAM))
        currencyList.add(CurrencyList("BBD", currencyModel!!.quotes.uSDBBD))
        currencyList.add(CurrencyList("BDT", currencyModel!!.quotes.uSDBDT))
        currencyList.add(CurrencyList("BGN", currencyModel!!.quotes.uSDBGN))
        currencyList.add(CurrencyList("BHD", currencyModel!!.quotes.uSDBHD))
        currencyList.add(CurrencyList("BND", currencyModel!!.quotes.uSDBND))
        currencyList.add(CurrencyList("BOB", currencyModel!!.quotes.uSDBOB))
        currencyList.add(CurrencyList("BRL", currencyModel!!.quotes.uSDBRL))
        currencyList.add(CurrencyList("BSD", currencyModel!!.quotes.uSDBSD))
        currencyList.add(CurrencyList("BTC", currencyModel!!.quotes.uSDBTC))
        currencyList.add(CurrencyList("BTN", currencyModel!!.quotes.uSDBTN))
        currencyList.add(CurrencyList("BWP", currencyModel!!.quotes.uSDBWP))
        currencyList.add(CurrencyList("BYN", currencyModel!!.quotes.uSDBYN))
        currencyList.add(CurrencyList("BZD", currencyModel!!.quotes.uSDBZD))
        currencyList.add(CurrencyList("CAD", currencyModel!!.quotes.uSDCAD))
        currencyList.add(CurrencyList("CDF", currencyModel!!.quotes.uSDCDF))
        currencyList.add(CurrencyList("CHF", currencyModel!!.quotes.uSDCHF))
        currencyList.add(CurrencyList("CLF", currencyModel!!.quotes.uSDCLF))
        currencyList.add(CurrencyList("CLP", currencyModel!!.quotes.uSDCLP))
        currencyList.add(CurrencyList("CNY", currencyModel!!.quotes.uSDCNY))
        currencyList.add(CurrencyList("COP", currencyModel!!.quotes.uSDCOP))
        currencyList.add(CurrencyList("CRC", currencyModel!!.quotes.uSDCRC))
        currencyList.add(CurrencyList("CUP", currencyModel!!.quotes.uSDCUP))
        currencyList.add(CurrencyList("CVE", currencyModel!!.quotes.uSDCVE))
        currencyList.add(CurrencyList("CZK", currencyModel!!.quotes.uSDCZK))
        currencyList.add(CurrencyList("DJF", currencyModel!!.quotes.uSDDJF))
        currencyList.add(CurrencyList("DKK", currencyModel!!.quotes.uSDDKK))
        currencyList.add(CurrencyList("DOP", currencyModel!!.quotes.uSDDOP))
        currencyList.add(CurrencyList("DZD", currencyModel!!.quotes.uSDDZD))
        currencyList.add(CurrencyList("EGP", currencyModel!!.quotes.uSDEGP))
        currencyList.add(CurrencyList("ERN", currencyModel!!.quotes.uSDERN))
        currencyList.add(CurrencyList("ETB", currencyModel!!.quotes.uSDETB))
        currencyList.add(CurrencyList("EUR", currencyModel!!.quotes.uSDEUR))
        currencyList.add(CurrencyList("FJD", currencyModel!!.quotes.uSDFJD))
        currencyList.add(CurrencyList("FKP", currencyModel!!.quotes.uSDFKP))
        currencyList.add(CurrencyList("GBP", currencyModel!!.quotes.uSDGBP))
        currencyList.add(CurrencyList("GEL", currencyModel!!.quotes.uSDGEL))
        currencyList.add(CurrencyList("GGP", currencyModel!!.quotes.uSDGGP))
        currencyList.add(CurrencyList("GHS", currencyModel!!.quotes.uSDGHS))
        currencyList.add(CurrencyList("GIP", currencyModel!!.quotes.uSDGIP))
        currencyList.add(CurrencyList("GMD", currencyModel!!.quotes.uSDGMD))
        currencyList.add(CurrencyList("GNF", currencyModel!!.quotes.uSDGNF))
        currencyList.add(CurrencyList("GTQ", currencyModel!!.quotes.uSDGTQ))
        currencyList.add(CurrencyList("GYD", currencyModel!!.quotes.uSDGYD))
        currencyList.add(CurrencyList("HKD", currencyModel!!.quotes.uSDHKD))
        currencyList.add(CurrencyList("HNL", currencyModel!!.quotes.uSDHNL))
        currencyList.add(CurrencyList("HRK", currencyModel!!.quotes.uSDHRK))
        currencyList.add(CurrencyList("HTG", currencyModel!!.quotes.uSDHTG))
        currencyList.add(CurrencyList("HUF", currencyModel!!.quotes.uSDHUF))
        currencyList.add(CurrencyList("IDR", currencyModel!!.quotes.uSDIDR))
        currencyList.add(CurrencyList("ILS", currencyModel!!.quotes.uSDILS))
        currencyList.add(CurrencyList("IMP", currencyModel!!.quotes.uSDIMP))
        currencyList.add(CurrencyList("INR", currencyModel!!.quotes.uSDINR))
        currencyList.add(CurrencyList("IRR", currencyModel!!.quotes.uSDIRR))
        currencyList.add(CurrencyList("ISK", currencyModel!!.quotes.uSDISK))
        currencyList.add(CurrencyList("JEP", currencyModel!!.quotes.uSDJEP))
        currencyList.add(CurrencyList("JMD", currencyModel!!.quotes.uSDJMD))
        currencyList.add(CurrencyList("JOD", currencyModel!!.quotes.uSDJOD))
        currencyList.add(CurrencyList("JPY", currencyModel!!.quotes.uSDJPY))
        currencyList.add(CurrencyList("KES", currencyModel!!.quotes.uSDKES))
        currencyList.add(CurrencyList("KGS", currencyModel!!.quotes.uSDKGS))
        currencyList.add(CurrencyList("KHR", currencyModel!!.quotes.uSDKHR))
        currencyList.add(CurrencyList("KMF", currencyModel!!.quotes.uSDKMF))
        currencyList.add(CurrencyList("KPW", currencyModel!!.quotes.uSDKPW))
        currencyList.add(CurrencyList("KRW", currencyModel!!.quotes.uSDKRW))
        currencyList.add(CurrencyList("KWD", currencyModel!!.quotes.uSDKWD))
        currencyList.add(CurrencyList("KYD", currencyModel!!.quotes.uSDKYD))
        currencyList.add(CurrencyList("KZT", currencyModel!!.quotes.uSDKZT))
        currencyList.add(CurrencyList("LAK", currencyModel!!.quotes.uSDLAK))
        currencyList.add(CurrencyList("LBP", currencyModel!!.quotes.uSDLBP))
        currencyList.add(CurrencyList("LKR", currencyModel!!.quotes.uSDLKR))
        currencyList.add(CurrencyList("LRD", currencyModel!!.quotes.uSDLRD))
        currencyList.add(CurrencyList("LSL", currencyModel!!.quotes.uSDLSL))
        currencyList.add(CurrencyList("LTL", currencyModel!!.quotes.uSDLTL))
        currencyList.add(CurrencyList("LVL", currencyModel!!.quotes.uSDLVL))
        currencyList.add(CurrencyList("LYD", currencyModel!!.quotes.uSDLYD))
        currencyList.add(CurrencyList("MAD", currencyModel!!.quotes.uSDMAD))
        currencyList.add(CurrencyList("MDL", currencyModel!!.quotes.uSDMDL))
        currencyList.add(CurrencyList("MGA", currencyModel!!.quotes.uSDMGA))
        currencyList.add(CurrencyList("MKD", currencyModel!!.quotes.uSDMKD))
        currencyList.add(CurrencyList("MMK", currencyModel!!.quotes.uSDMMK))
        currencyList.add(CurrencyList("MNT", currencyModel!!.quotes.uSDMNT))
        currencyList.add(CurrencyList("MOP", currencyModel!!.quotes.uSDMOP))
        currencyList.add(CurrencyList("MRO", currencyModel!!.quotes.uSDMRO))
        currencyList.add(CurrencyList("MUR", currencyModel!!.quotes.uSDMUR))
        currencyList.add(CurrencyList("MVR", currencyModel!!.quotes.uSDMVR))
        currencyList.add(CurrencyList("MWK", currencyModel!!.quotes.uSDMWK))
        currencyList.add(CurrencyList("MXN", currencyModel!!.quotes.uSDMXN))
        currencyList.add(CurrencyList("MYR", currencyModel!!.quotes.uSDMYR))
        currencyList.add(CurrencyList("MZN", currencyModel!!.quotes.uSDMZN))
        currencyList.add(CurrencyList("NAD", currencyModel!!.quotes.uSDNAD))
        currencyList.add(CurrencyList("NGN", currencyModel!!.quotes.uSDNGN))
        currencyList.add(CurrencyList("NIO", currencyModel!!.quotes.uSDNIO))
        currencyList.add(CurrencyList("NOK", currencyModel!!.quotes.uSDNOK))
        currencyList.add(CurrencyList("NPR", currencyModel!!.quotes.uSDNPR))
        currencyList.add(CurrencyList("NZD", currencyModel!!.quotes.uSDNZD))
        currencyList.add(CurrencyList("OMR", currencyModel!!.quotes.uSDOMR))
        currencyList.add(CurrencyList("PAB", currencyModel!!.quotes.uSDPAB))
        currencyList.add(CurrencyList("PEN", currencyModel!!.quotes.uSDPEN))
        currencyList.add(CurrencyList("PGK", currencyModel!!.quotes.uSDPGK))
        currencyList.add(CurrencyList("PHP", currencyModel!!.quotes.uSDPHP))
        currencyList.add(CurrencyList("PKR", currencyModel!!.quotes.uSDPKR))
        currencyList.add(CurrencyList("PLN", currencyModel!!.quotes.uSDPLN))
        currencyList.add(CurrencyList("PYG", currencyModel!!.quotes.uSDPYG))
        currencyList.add(CurrencyList("QAR", currencyModel!!.quotes.uSDQAR))
        currencyList.add(CurrencyList("RON", currencyModel!!.quotes.uSDRON))
        currencyList.add(CurrencyList("RSD", currencyModel!!.quotes.uSDRSD))
        currencyList.add(CurrencyList("RUB", currencyModel!!.quotes.uSDRUB))
        currencyList.add(CurrencyList("SAR", currencyModel!!.quotes.uSDSAR))
        currencyList.add(CurrencyList("SBD", currencyModel!!.quotes.uSDSBD))
        currencyList.add(CurrencyList("SCR", currencyModel!!.quotes.uSDSCR))
        currencyList.add(CurrencyList("SDG", currencyModel!!.quotes.uSDSDG))
        currencyList.add(CurrencyList("SEK", currencyModel!!.quotes.uSDSEK))
    }
}